server:
  port: 9090

spring:
  application:
    name: Complaints Service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/complaints_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 30000
          max-attempts: 5
          max-interval: 120000
          multiplier: 2.0
        default-requeue-rejected: false

  ai:
    openai:
      api-key: ${API_KEY}
      base-url: ${BASE_URL}
      chat:
        options:
          model: ${MODEL}
          temperature: 0.7
      embedding:
        enabled: false


    transformers:
      embedding:
        enabled: true
        onnx:
          model-uri: ${TE_MODEL}

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 384
        max-document-batch-size: 10000
        initialize-schema: true